# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from new_robot/Docking.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Docking(genpy.Message):
  _md5sum = "b6c8776d857a12b67acf562c20bdc3a5"
  _type = "new_robot/Docking"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool beginDocking
bool moveToBin
float64 arucoX
float64 arucoY
"""
  __slots__ = ['beginDocking','moveToBin','arucoX','arucoY']
  _slot_types = ['bool','bool','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       beginDocking,moveToBin,arucoX,arucoY

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Docking, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.beginDocking is None:
        self.beginDocking = False
      if self.moveToBin is None:
        self.moveToBin = False
      if self.arucoX is None:
        self.arucoX = 0.
      if self.arucoY is None:
        self.arucoY = 0.
    else:
      self.beginDocking = False
      self.moveToBin = False
      self.arucoX = 0.
      self.arucoY = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2d().pack(_x.beginDocking, _x.moveToBin, _x.arucoX, _x.arucoY))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.beginDocking, _x.moveToBin, _x.arucoX, _x.arucoY,) = _get_struct_2B2d().unpack(str[start:end])
      self.beginDocking = bool(self.beginDocking)
      self.moveToBin = bool(self.moveToBin)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2d().pack(_x.beginDocking, _x.moveToBin, _x.arucoX, _x.arucoY))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.beginDocking, _x.moveToBin, _x.arucoX, _x.arucoY,) = _get_struct_2B2d().unpack(str[start:end])
      self.beginDocking = bool(self.beginDocking)
      self.moveToBin = bool(self.moveToBin)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2d = None
def _get_struct_2B2d():
    global _struct_2B2d
    if _struct_2B2d is None:
        _struct_2B2d = struct.Struct("<2B2d")
    return _struct_2B2d
