// Generated by gencpp from file new_robot/Docking.msg
// DO NOT EDIT!


#ifndef NEW_ROBOT_MESSAGE_DOCKING_H
#define NEW_ROBOT_MESSAGE_DOCKING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace new_robot
{
template <class ContainerAllocator>
struct Docking_
{
  typedef Docking_<ContainerAllocator> Type;

  Docking_()
    : beginDocking(false)
    , moveToBin(false)
    , arucoX(0.0)
    , arucoY(0.0)  {
    }
  Docking_(const ContainerAllocator& _alloc)
    : beginDocking(false)
    , moveToBin(false)
    , arucoX(0.0)
    , arucoY(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _beginDocking_type;
  _beginDocking_type beginDocking;

   typedef uint8_t _moveToBin_type;
  _moveToBin_type moveToBin;

   typedef double _arucoX_type;
  _arucoX_type arucoX;

   typedef double _arucoY_type;
  _arucoY_type arucoY;





  typedef boost::shared_ptr< ::new_robot::Docking_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::new_robot::Docking_<ContainerAllocator> const> ConstPtr;

}; // struct Docking_

typedef ::new_robot::Docking_<std::allocator<void> > Docking;

typedef boost::shared_ptr< ::new_robot::Docking > DockingPtr;
typedef boost::shared_ptr< ::new_robot::Docking const> DockingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::new_robot::Docking_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::new_robot::Docking_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace new_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'new_robot': ['/home/arshad/rmc_2019/rmc_2019_ws/src/new_robot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::new_robot::Docking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_robot::Docking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_robot::Docking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_robot::Docking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_robot::Docking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_robot::Docking_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::new_robot::Docking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6c8776d857a12b67acf562c20bdc3a5";
  }

  static const char* value(const ::new_robot::Docking_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6c8776d857a12b6ULL;
  static const uint64_t static_value2 = 0x7acf562c20bdc3a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::new_robot::Docking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "new_robot/Docking";
  }

  static const char* value(const ::new_robot::Docking_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::new_robot::Docking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool beginDocking\n\
bool moveToBin\n\
float64 arucoX\n\
float64 arucoY\n\
";
  }

  static const char* value(const ::new_robot::Docking_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::new_robot::Docking_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.beginDocking);
      stream.next(m.moveToBin);
      stream.next(m.arucoX);
      stream.next(m.arucoY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Docking_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::new_robot::Docking_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::new_robot::Docking_<ContainerAllocator>& v)
  {
    s << indent << "beginDocking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.beginDocking);
    s << indent << "moveToBin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.moveToBin);
    s << indent << "arucoX: ";
    Printer<double>::stream(s, indent + "  ", v.arucoX);
    s << indent << "arucoY: ";
    Printer<double>::stream(s, indent + "  ", v.arucoY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEW_ROBOT_MESSAGE_DOCKING_H
